
package Ventanas.usuarios.Tarjeta;
import Ventanas.usuarios.InicioSesion.opcionescliente; 
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Ventanas.usuarios.Cotizacion.cotizacioncliente;

public class registrotarjetas extends javax.swing.JFrame {
  
    public static  ArrayList<Tarjeta> tarjetas = new ArrayList<>();
    
    public void boton(boolean valor)
    {
    txtnombretar.setEditable(valor);
    txtnombretar.setEnabled(valor);
    txtnumerotar.setEditable(valor);
    txtnumerotar.setEnabled(valor);
    txtfechatar.setEditable(valor);
    txtfechatar.setEnabled(valor);
    btnguardar.setEnabled(valor);
    btnEliminar.setEnabled(valor);
    btnModificar.setEnabled(valor);
    atras.setEnabled(valor);
    CVV.setEditable(!valor);
    CVV.setEnabled(!valor);
    txtCVV.setEnabled(!valor);
    Cerrar.setEnabled(!valor);
    PAGAR.setEnabled(!valor);
    }
    public void cambio(){
        atras.setEnabled(false);
        Cerrar.setEnabled(true);
        btnEliminar.setEnabled(false);
        btnModificar.setEnabled(false);
    }
    
    
    public void iniciarTarjeta(){
        System.out.println(correo);
        String[] columnas = {"Nombre","Numero","Fecha"};
            DefaultTableModel modelo = new DefaultTableModel(columnas, 0);

            for(int i = 0;i<Logic.tamaño();i++)
            {
                String tarjeta = "";
                if(Logic.completa(i).getUsuario().equalsIgnoreCase(correo)){
                    int numero = Logic.completa(i).getNumerotar().length();
                    if(numero>=4)
                    {
                        
                        String ultimos4 = Logic.completa(i).getNumerotar().substring(numero-4);
                        tarjeta = "";
                        for(int a = 0; a<numero-4;a++){
                            tarjeta+="X";
                        }
                        tarjeta += ultimos4;
                        
                    }else{
                        tarjeta = Logic.completa(i).getNumerotar();
                    }
                    
                Object[] fila = 
                {Logic.completa(i).getNombretar(),tarjeta, 
                Logic.completa(i).getFechatar()};
                modelo.addRow(fila);
                }
             }
             jTable1.setModel(modelo);
    }
    
    
    /**
     * Creates new form registrotarjetas
     */
    public registrotarjetas() {
        initComponents();
         this.setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        atras = new javax.swing.JButton();
        txtnombretar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtnumerotar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtfechatar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnguardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        CVV = new javax.swing.JTextField();
        txtCVV = new javax.swing.JLabel();
        Cerrar = new javax.swing.JButton();
        PAGAR = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        txtmodificar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        atras.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        atras.setText("Atrás");
        atras.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                atrasActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre de la tarjeta: ");

        jLabel2.setText("Número de la tarjeta: ");

        jLabel3.setText("Fecha de vencimiento: ");

        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnguardarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setToolTipText("");
        jScrollPane1.setViewportView(jTable1);

        CVV.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        CVV.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                CVVActionPerformed(evt);
            }
        });

        txtCVV.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        txtCVV.setText("CVV");

        Cerrar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Cerrar.setText("CERRAR");
        Cerrar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                CerrarActionPerformed(evt);
            }
        });

        PAGAR.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        PAGAR.setText("PAGAR");
        PAGAR.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                PAGARActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnEliminarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnModificarActionPerformed(evt);
            }
        });

        txtmodificar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(txtnombretar)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                    .addComponent(txtnumerotar)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtfechatar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addComponent(atras)
                    .addComponent(txtmodificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCVV, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CVV, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PAGAR)
                        .addGap(59, 59, 59)
                        .addComponent(Cerrar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnModificar)
                            .addGap(18, 18, 18)
                            .addComponent(btnEliminar))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtnombretar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnumerotar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfechatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnguardar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEliminar)
                            .addComponent(btnModificar)
                            .addComponent(txtmodificar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Cerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCVV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(PAGAR)
                                .addComponent(CVV)))
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(atras)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        opcionescliente o = new opcionescliente(); 
        o.setVisible(true);
        o.setCorreoU(correo);
        o.setRol(rol);
        this.dispose();
        o.nombre();
    }//GEN-LAST:event_atrasActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        
        if(modificar==false)
        {
            String nom = txtnombretar.getText(); 
            String num = txtnumerotar.getText(); 
            String fec = txtfechatar.getText(); 

              if(!nom.isEmpty() && !num.isEmpty() && !fec.isEmpty()){

                Tarjeta temporal = new Tarjeta(nom,num,fec,correo); 
                 if(Logic.insertar(temporal))
                 {
                     JOptionPane.showMessageDialog(this,"Tarjeta registrada");
                     txtnombretar.setText("");
                     txtnumerotar.setText("");
                     txtfechatar.setText("");
                     iniciarTarjeta();
                 }else{
                     JOptionPane.showMessageDialog(this,"Tarjeta existente");
                 }

             }else{
                  JOptionPane.showMessageDialog(this, "Hay campos vacios");
              }
        
        }else{
            
            btnguardar.setText("ACTUALIZAR");
            
            String nom = txtnombretar.getText(); 
            String num = txtnumerotar.getText(); 
            String fec = txtfechatar.getText(); 

              if(!nom.isEmpty() && !num.isEmpty() && !fec.isEmpty()){

                    String no= Tarjeta();
                    if(!no.equalsIgnoreCase("vacio"))
                    {
                        for(int i =0;i< Logic.tamaño();i++){
                            if(Logic.completa(i).getNumerotar().equalsIgnoreCase(no))
                            {

                               if(Logic.buscar(correo, num)==-1){

                                   Logic.completa(i).setFechatar(fec);
                                   Logic.completa(i).setNombretar(nom);
                                   Logic.completa(i).setNumerotar(num);
                                   btnguardar.setText("Guardar");
                                   setModificar(false);
                                   txtnombretar.setText("");
                                   txtnumerotar.setText("");
                                   txtmodificar.setText("");
                                   txtfechatar.setText("");
                                   jTable1.setEnabled(true);
                                   iniciarTarjeta();
                                   
                               }else{
                                   JOptionPane.showMessageDialog(this, "Tarjeta existente");
                                   
                                   txtnombretar.setText("");
                                   txtnumerotar.setText("");
                                   txtfechatar.setText("");
                               }

                            }
                        }
                    }else{
                        JOptionPane.showMessageDialog(this, "Seleccione una tarjeta");
                    }
                    
             }else{
                  JOptionPane.showMessageDialog(this, "Hay campos vacios");
              }
        
        }
        
    }//GEN-LAST:event_btnguardarActionPerformed

    public String Tarjeta(){
    int row = jTable1.getSelectedRow();
    int column = 1; // seleccionamos la segunda columna
    String value = "vacio";
    if(row!=-1){
       String a = jTable1.getModel().getValueAt(row, column).toString();  
        if(!a.isEmpty()){
            value = a;
            
            if(!CVV.getText().isEmpty()){
                setCVV(CVV.getText());
            }else{
                JOptionPane.showMessageDialog(this, "Falta de CVV");
            }
            
        }else{
            System.out.println("Datos vacios");
            value="vacio";
            setCVV("vacio");
        }
    }else{
        setCVV("vacio");
        value = "vacio";
    }
    return value;
    }
    
    
    private void PAGARActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_PAGARActionPerformed
    {//GEN-HEADEREND:event_PAGARActionPerformed
        setTar(Tarjeta());
        
        if(!tar.isEmpty() && !cvv.isEmpty()){
        JOptionPane.showMessageDialog(this, "Tarjeta lista");
        this.dispose();
        }else{
            JOptionPane.showMessageDialog(this, "Falta de cvv");
        }
        
        
    }//GEN-LAST:event_PAGARActionPerformed

    private void CerrarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CerrarActionPerformed
    {//GEN-HEADEREND:event_CerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_CerrarActionPerformed

    private void CVVActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CVVActionPerformed
    {//GEN-HEADEREND:event_CVVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CVVActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnEliminarActionPerformed
    {//GEN-HEADEREND:event_btnEliminarActionPerformed
           if(administrar())
           {
            CVV.setEnabled(true);
            CVV.setEditable(true);
            CVV.setText("Eliminando");
            CVV.setEditable(false);
            CVV.setEnabled(false);

            String no= Tarjeta();
            
            if(!no.equalsIgnoreCase("vacio")){
                for(int i =0;i< Logic.tamaño();i++){
                if(Logic.completa(i).getNumerotar().equalsIgnoreCase(no)){
                    System.out.println("Tarjeta eliminada "+Logic.completa(i).getNumerotar());
                    Logic.eliminar(i);
                }
            }
                iniciarTarjeta();
            }else{
                JOptionPane.showMessageDialog(this, "Seleccione una tarjeta");
            }
            
           }else{
               JOptionPane.showMessageDialog(this, "No hay tarjetas");
           }
           
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnModificarActionPerformed
    {//GEN-HEADEREND:event_btnModificarActionPerformed
           if(administrar())
           {
               String nombre = Tarjeta();
               
               if(!nombre.equalsIgnoreCase("vacio")){
                   
                   
                CVV.setEnabled(true);
                CVV.setEditable(true);
                CVV.setText("Modificando");
                CVV.setEditable(false);
                CVV.setEnabled(false);
                
                setModificar(true);
                txtmodificar.setText("Esta modificando el registro: "+nombre);
                jTable1.setEnabled(false);
                btnguardar.setText("ACTUALIZAR");
            
               }else{
                   JOptionPane.showMessageDialog(this, "Seleccione tarjeta");
               }
               
           }else{
               setModificar(false);
               JOptionPane.showMessageDialog(this, "No hay tarjetas");
           }
            
    }//GEN-LAST:event_btnModificarActionPerformed
    
    public boolean administrar(){
        
        if(Logic.tamaño()>0){
            return true;
        }else{
            return false;
        }
           
    }
    
    
    
    // -------------------------------------------------------------------------
    private String correo;
    
    public void setCorreoU(String correo){
        this.correo = correo;
    }
    // -------------------------------------------------------------------------
    private static String cvv = "vacio";
    private static String tar = "vacio";
    
    public void setCVV(String cvv){
        this.cvv = cvv;
    }
    public static String getCVV(){
        return cvv;
    }
    
    public void setTar(String tar){
        this.tar = tar;
    }
    public static String getTar(){
        return tar;
    }
    // -------------------------------------------------------------------------
     private String rol;
    public void setRol(String rol){
        this.rol = rol;
    }
    // -------------------------------------------------------------------------
    private boolean modificar = false;
    public void setModificar(boolean valor){
        this.modificar = valor;
    }
    // -------------------------------------------------------------------------
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrotarjetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrotarjetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrotarjetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrotarjetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registrotarjetas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CVV;
    private javax.swing.JButton Cerrar;
    private javax.swing.JButton PAGAR;
    private javax.swing.JButton atras;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel txtCVV;
    private javax.swing.JTextField txtfechatar;
    private javax.swing.JLabel txtmodificar;
    private javax.swing.JTextField txtnombretar;
    private javax.swing.JTextField txtnumerotar;
    // End of variables declaration//GEN-END:variables
}
