
package Ventanas.usuarios.Admin;
import Ventanas.usuarios.Admin.Logica;
import Ventanas.usuarios.InicioSesion.PaginaPrincipal;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class RegionesPrecio extends javax.swing.JFrame
{

    
    public RegionesPrecio()
    {
        initComponents();
    }
    
    public void iniciarRegiones(){
        btnguardar.setEnabled(false);
        System.out.println("Oprimido");
        String[] columnas = {"Codigo","Nombre Region","Precio Estandar", "Precio Especial"};
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0);
        int z = Logica.tamañoR();
        for(int a = 0; a<z;a++)
        {
            Object[] fila = {Logica.imprimirR(a).getNombreregion(),
                Logica.imprimirR(a).getCodigo(),
                Logica.imprimirR(a).getPrecioEstandar(),
                Logica.imprimirR(a).getPrecioEspecial()};
            modelo.addRow(fila);
        }
        tabla.setModel(modelo);
        
    }

    public String Tarjeta(){
    int row = tabla.getSelectedRow();
    int column = 0; // seleccionamos la segunda columna
    String value = "vacio";
    if(row!=-1){
       String a = tabla.getModel().getValueAt(row, column).toString();  
        if(!a.isEmpty()){
            value = a;
            
        }else{
            System.out.println("Datos vacios");
            value="vacio";  
        }
    }else{
        value = "vacio";
    }
    return value;
    }
     
     public boolean administrar(){
        
        if(Logica.tamañoR()>0){
            return true;
        }else{
            return false;
        }
           
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        atras = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtestandar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtespecial = new javax.swing.JTextField();
        btnguardar = new javax.swing.JButton();
        txtmodificar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Informacion de Regiones");

        atras.setText("Atras");
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });

        tabla.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre region");

        jLabel3.setText("Codigo");

        jLabel4.setText("Precio estandar");

        jLabel5.setText("Precio especial");

        txtespecial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtespecialActionPerformed(evt);
            }
        });

        btnguardar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnguardar.setText("Modificar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        txtmodificar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(atras)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(230, 230, 230))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnModificar)
                            .addGap(18, 18, 18)
                            .addComponent(btnEliminar))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(35, 35, 35))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(42, 42, 42)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtestandar, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                            .addComponent(txtnombre))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(65, 65, 65)
                                .addComponent(txtcodigo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtespecial, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnguardar)
                        .addGap(58, 58, 58)
                        .addComponent(txtmodificar, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtestandar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtespecial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtmodificar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnguardar))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(btnModificar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(atras)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atrasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_atrasActionPerformed
    {//GEN-HEADEREND:event_atrasActionPerformed
      opciones2 volver = new opciones2();
      volver.setCorreoU(correo);
      volver.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_atrasActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnEliminarActionPerformed
    {//GEN-HEADEREND:event_btnEliminarActionPerformed
       if(administrar())
           {
            String no= Tarjeta();
            if(!no.equalsIgnoreCase("vacio")){
                for(int i =0;i< Logica.tamañoR();i++){
                if(Logica.imprimirR(i).getNombreregion().equalsIgnoreCase(no)){
                    System.out.println("Region eliminada "+Logica.imprimirR(i).getNombreregion());
                    Logica.eliminarR(i);
                }
            }
            iniciarRegiones();
            }else{
                JOptionPane.showMessageDialog(this, "Seleccione una region");
            }
            
           }else{
               JOptionPane.showMessageDialog(this, "No hay regiones");
           }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnModificarActionPerformed
    {//GEN-HEADEREND:event_btnModificarActionPerformed
        if(administrar())
           {
            String nombre = Tarjeta();
               if(!nombre.equalsIgnoreCase("vacio")){
                   btnguardar.setEnabled(true);
                    setModificar(true);
                txtmodificar.setText("Esta modificando el registro: "+nombre);
                tabla.setEnabled(false);
                btnguardar.setText("ACTUALIZAR");
            
               }else{
                   JOptionPane.showMessageDialog(this, "Seleccione region");
               }
            
           }else{
                 setModificar(false);
                 JOptionPane.showMessageDialog(this, "No hay regiones");
           }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void txtespecialActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtespecialActionPerformed
    {//GEN-HEADEREND:event_txtespecialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtespecialActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnguardarActionPerformed
    {//GEN-HEADEREND:event_btnguardarActionPerformed
       
        if(modificar==false){
            
        }else{
            btnguardar.setText("ACTUALIZAR");
            
            String nom = txtnombre.getText();
            String codigo = txtcodigo.getText();
            String estandar = txtestandar.getText();
            String especial = txtespecial.getText();

              if(!nom.isEmpty() && !codigo.isEmpty() && !estandar.isEmpty()&& !especial.isEmpty()){

                    String no= Tarjeta();
                    if(!no.equalsIgnoreCase("vacio"))
                    {
                        for(int i =0;i< Logica.tamañoR();i++){
                            if(Logica.imprimirR(i).getNombreregion().equalsIgnoreCase(no))
                            {

                               if(Logica.buscarR(Logica.imprimirR(i).getNombreregion())==-1){

                                  Logica.imprimirR(i).setNombreregion(codigo);
                                  Logica.imprimirR(i).setCodigo(nom);
                                  double esp = Double.parseDouble(especial);
                                  Logica.imprimirR(i).setEspecial(esp);
                                  double est = Double.parseDouble(estandar);
                                  Logica.imprimirR(i).setEstandar(est);
                                  
                                  
                                   btnguardar.setText("Modificar");
                                   setModificar(false);
                                   btnguardar.setEnabled(true);
                                   txtnombre.setText("");
                                   txtcodigo.setText("");
                                   txtestandar.setText("");
                                   txtespecial.setText("");
                                    txtmodificar.setText("");
                                   tabla.setEnabled(true);
                                   
                                   iniciarRegiones();
                                   
                               }else{
                                   JOptionPane.showMessageDialog(this, "Region existente");
                                  
                                   txtnombre.setText("");
                                   txtcodigo.setText("");
                                   txtestandar.setText("");
                                   txtespecial.setText("");
                                   
                               }

                            }
                        }
                    }else{
                        JOptionPane.showMessageDialog(this, "Seleccione una region");
                    }
        }
        
        }   
    }//GEN-LAST:event_btnguardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(RegionesPrecio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(RegionesPrecio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(RegionesPrecio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(RegionesPrecio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new RegionesPrecio().setVisible(true);
            }
        });
    }
    // -------------------------------------------------------------------------
    private String correo;
    
    public void setCorreoU(String correo){
        this.correo = correo;
    }
    // -------------------------------------------------------------------------
     private boolean modificar = false;
    public void setModificar(boolean valor){
        this.modificar = valor;
    }
    // -------------------------------------------------------------------------
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atras;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtespecial;
    private javax.swing.JTextField txtestandar;
    private javax.swing.JLabel txtmodificar;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
